# hexo-theme-indigo
# https://github.com/yscoder/hexo-theme-indigo

# 添加新菜单项遵循以下规则
# menu:
#  link:               fontawesome图标，省略前缀，本主题前缀为 icon-，必须
#    text: About       菜单显示的文字，如果省略即默认与图标一致，首字母会转大写
#    url: /about       链接，绝对或相对路径，必须。
#    target: _blank    是否跳出，省略则在当前页面打开
menu:
  home:
    text: 主页
    url: /
  archives:
    text: 归档
    url: /archives
  tags:
    text: 标签
    url: /tags
  th-list:
    text: 分类
    url: /categories
  user:
    text: 关于
    url: /about
  github:
    text: GitHub
    url: https://github.com/athlonreg
    target: _blank
  apple:
    text: Daliansky
    url: https://blog.Daliansky.net
    target: _blank
  feed:
    text: Feed
    url: https://blog.iamzhl.top/atom.xml
    target: _blank

# 你的头像url
avatar: /img/avatar.jpg
# avatar link
avatar_link: /
# 头像背景图
brand: /img/brand.jpg
# favicon
favicon: /favicon.ico

# email
email: 15563836030@163.com

# 设置 Android L Chrome 浏览器状态栏颜色
color: '#3F51B5'

# 页面标题
tags_title: Tags
archives_title: Archives
categories_title: Categories

# 文章截断
excerpt_render: false
excerpt_length: 200
excerpt_link: 阅读全文...
mathjax: true
archive_yearly: true

# 是否显示文章最后更新时间
show_last_updated: true

# 是否开启分享
share: true

# 是否开启打赏，关闭 reward: false
reward:
  title: 请博主喝杯咖啡吧~
  wechat: /img/wechat.jpg     #微信，关闭设为 false
  alipay: /img/alipay.jpg     #支付宝，关闭设为 false

# 是否开启搜索
search: true

# 是否大屏幕下文章页隐藏导航
hideMenu: true

# 是否开启toc
# toc: false
toc:
  list_number: true  # 是否显示数字排序

# 文章页留言内容，hexo中所有变量及辅助函数等均可调用，具体请查阅 hexo.io
postMessage: 尊重作者劳动成果，转载请注明原出处´◡` <a href="<%- url_for(page.path).replace(/index\.html$/, '') %>" target="_blank" rel="external"><%- page.permalink.replace(/index\.html$/, '') %></a>

# 站长统计，如要开启，输入CNZZ站点id，如 cnzz: 1255152447
cnzz: false

# 百度统计，如要开启，改为你的 key
baidu_tongji: false

# 腾讯分析，如要开启，输入站点id
tajs: false

# google
google_analytics: false
google_site_verification: false

# sogou站长验证 http://zhanzhang.sogou.com/
sogou_site_verification: false

# less
less:
  compress: true
  paths:
    - source/css/style.less

# 以下评论插件开启一个即可
# 是否开启 disqus
disqus_shortname: false
# 是否开启友言评论, 填写友言用户id
uyan_uid: false
# 是否使用 gitment，https://github.com/imsun/gitment
gitment: false
owner: athlonreg
repo: git-comment
client_id: 2532600737516ae73769
client_secret: 5447e3b58a359bae698dcac5318ec956949b2163

# use gitalk://github.com/gitalk/gitalk
# gitalk: true
#  owner: 
#  repo: 
#  client_id: 
#  client_secret: 
gitalk:
  enable: true
  owner: athlonreg  # 例：asdfv1929   
  repo: gittalk   # 例：asdfv1929.github.io
  client_id: 2fa40fcfb4a9f851c22b
  client_secret: 6fa9995849a674bf227662f9dff8a02f03c23dfa
  admin: athlonreg #指定可初始化评论账户
  distractionFreeMode: true

# Valine Comment system. https://valine.js.org
valine:
  enable: false
  appId:
  appKey:
  notify: false
  verify: false
  avatar: mm
  placeholder: Just go go
  guest_info: nick,mail,link
  pageSize: 10
# valine:
#   enable: true # 如果你想使用valine，请将值设置为 true
#   appId: k1qv17ho3MJ13J73ybcPSzdS-gzGzoHsz # your leancloud appId
#   appKey: vXRKLu09Vu3krwPWN3hXIuBQ # your leancloud appKey
#   notify: true # Mail notify
#   verify: true # Verify code
#   avatar: mm # Gravatar style : mm/identicon/monsterid/wavatar/retro/hide
#   placeholder: 给博主留言... # Comment Box placeholder
#   guest_info: nick,mail,link # Comment header info
#   pageSize: 10 # comment list page size

# 是否开启Hyper Comments，填写id则启用，false则禁用。http://hypercomments.com
# Hyper Comments support. Write your id here, or false to disable
hyper_id: false


# 规范网址
# 让搜索引擎重定向你的不同域名、不同子域、同域不同目录的站点到你期望的路径
# https://support.google.com/webmasters/answer/139066
# 假设配置为 canonical: http://imys.net，那么从搜索引擎中 www.imys.net 进入会重定向到 imys.net
canonical: https://blog.iamzhl.top

# 版权起始年份
since_year: 2017

# 用户页面中作者相关的描述性文字，如不需要设为 false
about: 一个Linux运维热爱者，同时也是一个PC极客发烧友

# “不蒜子”访问量统计，详见 http://ibruce.info/2015/04/04/busuanzi/
visit_counter:
  site_uv: 站点总访客数：
  site_pv: 站点总访问量：

# 动态定义title
title_change:
  normal: (つェ⊂)咦!又好了!
  leave: 死鬼去哪里了！

# 设置为 true 发布后将使用 unpkg cdn 最新的主题样式
# 如果想让你的自定义样式生效，把此项设为 false
cdn: true

# 设置为 true 将使用 lightbox render 图片
lightbox: true

# icp备案号  ICP_license: 京ICP备1234556号-1
ICP_license: false

# daovoice
daovoice: false
daovoice_app_id: 2ec55fb7  # 这里填你刚才获得的 app_id
